Repository I-Fit/I-Fit, pull requests merged in 2024-07, with the labels that each got.

#4 one 기능 개발 완료
  one.txt
Labels: enhancement

#5 two 기능 개발
  two.txt
Labels: enhancement

#7 4 기능 개발
  four.txt
Labels: enhancement

#9 conf2
  README.md
Labels: enhancement

#11 payment 기능 개발
  payment.txt
Labels: enhancement

#14 Create pull_request_template.md
  .github/pull_request_template.md
Labels: 📝docs

#17 test
  01.Frontend/.vscode/settings.json
  test.txt
Labels: ⚡ feat

#20 Feature/login
  test2.txt
  test3.txt
Labels: ✅ test

#21 Feature/test
  test2.txt
Labels: ✅ test

#23 messi
  test4.txt
Labels: ✅ test

#25 jojo-test
  jojo.txt
Labels: ✅ test

#29 modify
  01.Frontend/1. 메인페이지/main.css
  01.Frontend/1. 메인페이지/main.html
  01.Frontend/10. 나의 참여내역/모임 참여내역.css
  01.Frontend/10. 나의 참여내역/모임 참여내역.html
  01.Frontend/11. 찜한 모임내역/찜한 모임 내역.css
  01.Frontend/11. 찜한 모임내역/찜한 모임 내역.html
  01.Frontend/13. 멤버십 결제/membership_payment.css
  01.Frontend/14. 모임 생성/create_group.css
  01.Frontend/14. 모임 생성/create_group.html
  01.Frontend/15. 게시글 메인/frame.css
  01.Frontend/15. 게시글 메인/index.html
  01.Frontend/15. 게시글 메인/main.css
  01.Frontend/16. 게시글 상세/frame.css
  01.Frontend/16. 게시글 상세/index.html
  01.Frontend/16. 게시글 상세/main.css
  01.Frontend/17. 게시글 수정/frame.css
  01.Frontend/17. 게시글 수정/index.html
  01.Frontend/17. 게시글 수정/main.css
  01.Frontend/19. 나의 게시글/나의 게시물 내역.css
  01.Frontend/19. 나의 게시글/나의 게시물 내역.html
  01.Frontend/2. 회원가입/create_account.css
  01.Frontend/2. 회원가입/create_account.html
  01.Frontend/20. 내가 쓴 댓글/내가 쓴 댓글 내역.css
  01.Frontend/20. 내가 쓴 댓글/내가 쓴 댓글 내역.html
  01.Frontend/21. 내가 좋아요한 게시글/내가 좋아요한 게시글.css
  01.Frontend/21. 내가 좋아요한 게시글/내가 좋아요한 게시글.html
  01.Frontend/3. 이용약관 동의/tos.css
  01.Frontend/3. 이용약관 동의/tos.html
  01.Frontend/4. 로그인/login.css
  01.Frontend/4. 로그인/login.html
  01.Frontend/5. 아이디 찾기/find_id.css
  01.Frontend/5. 아이디 찾기/find_id.html
  01.Frontend/6. 아이디 찾기 완료/find_id_complete.css
  01.Frontend/7. 비밀번호 재설정/find_pw.css
  01.Frontend/7. 비밀번호 재설정/find_pw.html
  01.Frontend/8. 마이페이지/frame.css
  01.Frontend/8. 마이페이지/main.css
  01.Frontend/img/google.PNG
  01.Frontend/img/kakao.PNG
  01.Frontend/img/naver.PNG
  01.Frontend/test.txt
Labels: ✅ test

#27 test
  test.txt
Labels: ✅ test

#32 hometest
  hometest.txt
Labels: jihoon

#34 backhome
  02.Backend/backhometest.txt
Labels: jihoon

#37 push-test
  test.txt
Labels: ✅ test

#39 modify-frontend
  01.Frontend/1. 메인페이지/main.css
  01.Frontend/1. 메인페이지/main.html
  01.Frontend/10. 나의 참여내역/모임 참여내역.css
  01.Frontend/10. 나의 참여내역/모임 참여내역.html
  01.Frontend/11. 찜한 모임내역/찜한 모임 내역.css
  01.Frontend/11. 찜한 모임내역/찜한 모임 내역.html
  01.Frontend/12. 멤버십 메인/membership_main.css
  01.Frontend/13. 멤버십 결제/membership_payment.css
  01.Frontend/15. 게시글 메인/frame.css
  01.Frontend/15. 게시글 메인/index.html
  01.Frontend/15. 게시글 메인/main.css
  01.Frontend/16. 게시글 상세/frame.css
  01.Frontend/16. 게시글 상세/index.html
  01.Frontend/16. 게시글 상세/main.css
  01.Frontend/19. 나의 게시글/나의 게시물 내역.css
  01.Frontend/19. 나의 게시글/나의 게시물 내역.html
  01.Frontend/20. 내가 쓴 댓글/내가 쓴 댓글 내역.css
  01.Frontend/20. 내가 쓴 댓글/내가 쓴 댓글 내역.html
  01.Frontend/21. 내가 좋아요한 게시글/내가 좋아요한 게시글.html
  01.Frontend/21. 내가 좋아요한 게시글/좋아요 한 게시글.css
  01.Frontend/4. 로그인/login.html
  01.Frontend/8. 마이페이지/frame.css
  01.Frontend/8. 마이페이지/index.html
  01.Frontend/8. 마이페이지/main.css
  01.Frontend/img/black-heart.png
  01.Frontend/img/comment.png
  01.Frontend/img/comment_icon.png
  01.Frontend/img/dot.png
  01.Frontend/img/heart.png
  01.Frontend/img/white_heart_icon.png
  01.Frontend/img/수정_icon.png
Labels: 🎈 frontend

#43 0722_modify
  01.Frontend/1. 메인페이지/main.css
  01.Frontend/1. 메인페이지/main.html
  01.Frontend/10. 나의 참여내역/모임 참여내역.css
  01.Frontend/10. 나의 참여내역/모임 참여내역.html
  01.Frontend/11. 찜한 모임내역/찜한 모임 내역.css
  01.Frontend/11. 찜한 모임내역/찜한 모임 내역.html
  01.Frontend/2. 회원가입/create_account.css
  01.Frontend/2. 회원가입/create_account.html
  01.Frontend/20. 내가 쓴 댓글/내가 쓴 댓글 내역.css
  01.Frontend/20. 내가 쓴 댓글/내가 쓴 댓글 내역.html
  01.Frontend/4. 로그인/login.css
  01.Frontend/4. 로그인/login.html
  01.Frontend/5. 아이디 찾기/find_id.css
  01.Frontend/5. 아이디 찾기/find_id.html
  01.Frontend/6. 아이디 찾기 완료/find_id_complete.css
  01.Frontend/6. 아이디 찾기 완료/find_id_complete.html
  01.Frontend/7. 비밀번호 재설정/find_pw.css
  01.Frontend/7. 비밀번호 재설정/find_pw.html
  01.Frontend/8. 마이페이지/frame.css
  01.Frontend/8. 마이페이지/index.html
  01.Frontend/8. 마이페이지/main.css
  01.Frontend/9. 회원탈퇴/회원탈퇴.css
  01.Frontend/9. 회원탈퇴/회원탈퇴.html
Labels: 🎈 frontend
